### ISSUE TITLE
How do I put my username inside the file?

### ISSUE THREAD

**Issue by Darealmxone** [xadhrit/terra#8]
I can't open creds/insta.yml and i also don't understand how I'm supposed to put my username there :/

**Comment by xadhrit** [comment]
huh? If there is no creds/insta.yml in a folder on your system or if you have any other problem with that, then just delete the creds folder and create a new folder named creds and create two files insta.yml and twitter.yml inside of creds folder.
After creating files inside the creds folder, open the insta.yml and put your Instagram username and password like :
    `username: your_username`
    `password: your_password`

**Comment by Darealmxone** [comment]
I see, thank you!! (Sorry for the dumb request, am a noob).

**Comment by Darealmxone** [comment]
It's working now, i love it!!

**Comment by xadhrit** [comment]
nice ! Keep learning keep sharing!!
Closing the issue for now. Please follow up.
